config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  root 'welcome#index'

  get 'home' => 'welcome#index'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    if params[:country] == nil 
      @destinations = Destination.all
    else
      @destinations = Destination.where(country: params[:country].titleize)
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	 @homeland = "Springfield, Massachussetts"
  	 @countries = ['Boston','Atlanta','New York','Memphis']
  	 @images = ['boston.jpg','atlanta.jpg','newyork.jpg','memphis.jpg']
  end

  def about
  	 @color = params[:color]
  	 @size = params[:size].to_i
  end

  def contact
 	 @color = params[:color]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: "5" %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>


<h1>My Destination Wish List</h1>

  <div class="row">
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= destination.city %></h2>
         <h3<%= destination.country %></h3>
         <p><%= destination.description %></p>
       
         <div class="btn-group">
          <%= link_to 'Show', destination, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-default" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Destination', new_destination_path, class: "btn btn-primary" %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<h1><%= @destination.city %>, <%= @destination.country %></h1>

<p> <%= @destination.description %></p>

<div class="btn-group">
  <%= link_to 'Edit', edit_destination_path(@destination), class: "btn btn-default" %> 
  <%= link_to 'Back', destinations_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <link href='http://fonts.googleapis.com/css?family=Marck+Script' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Creativ//Creature", root_path, class: "navbar-brand" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path  %></li>  
        <li><%= link_to "Destinations", destinations_path  %></li>       
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Howdy Howdy you Bout it Bout it?</h1>
<p>Lots of interesting stuffs.</p>
<p>My favorite color is <%= @color %></p>

<style>
  body {
    background: <%= @color %>;
  }
</style>


<% if @size > 12 %>

	<p>I wear size <%= @size %></p>
	<p>I have HUGE feet!!</p>

<%else%>
	<p>I wear size <%= @size %></p>
<% end %>  


<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %>
<%= link_to "Red", about_path(color: "red"), class: "btn btn-danger" %>
<%= link_to "Yellow", about_path(color: "yellow"), class: "btn btn-success" %>
<%= link_to "Orange", about_path(color: "orange"), class: "btn btn-primary" %>
<br/><br/>

<%= link_to "15", about_path(size: "15"), class: "btn btn-primary" %>
<%= link_to "10", about_path(size: "10"), class: "btn btn-primary" %>
<%= link_to "4", about_path(size: "4"), class: "btn btn-primary" %>

app/views/welcome/contact.html.erb
<style>
  .fontbaby {
    color: <%= @color %>;
  }
</style>
<h1 class="fontbaby">This is a contact page</h1>
<p>Hit me up chrisparker@shutyoface.org</p>



<%= link_to "Blue", contact_path(color: "blue"), class: "btn btn-primary" %>
<%= link_to "Red", contact_path(color: "red"), class: "btn btn-danger" %>
<%= link_to "Yellow", contact_path(color: "yellow"), class: "btn btn-success" %>
<%= link_to "Orange", contact_path(color: "orange"), class: "btn btn-primary" %>

app/views/welcome/index.html.erb
<div class="jumbotron"><h1>WELCOME TO THE TRAVEL PAGE OF YOUR DREAMS!!</h1>
<p>Find me in <%= @homeland %></p></div>

<ol>
	<% @countries.each do |country| %>
  		<li><%= country %></li>
	<% end %>
</ol>


<style>
  body {
    background: <%= @color %>;
  }
</style>

<% @images.shuffle!%>

<% @images.each do |image_name| %>
	<%= image_tag image_name ,height: 300, width: 400 %>
<% end %>  

<!--<% @images.each do |image_name| %>

	<%= image_tag image_name ,:height => "10%", :width => "10%" %>

<% end %>  -->